Row Failed: 7
list index out of rangeTraceback (most recent call last):
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\link_scrape.py", line 184, in review_volume
    number_reviews = int((overview_data.text.split(
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\link_scrape.py", line 325, in grab_review_data
    dic = data_attach(dic, row, country)
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\link_scrape.py", line 275, in data_attach
    counts = scrape_count(links, country)
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\link_scrape.py", line 208, in scrape_count
    seek_count = review_volume(seek_soup, "Seek", seek_url)
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\link_scrape.py", line 188, in review_volume
    re.findall(r'total rating from ([0-9]+)', overview_data.text)[0])
IndexError: list index out of range


Row Failed: 19
list index out of rangeTraceback (most recent call last):
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\link_scrape.py", line 184, in review_volume
    number_reviews = int((overview_data.text.split(
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\link_scrape.py", line 325, in grab_review_data
    dic = data_attach(dic, row, country)
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\link_scrape.py", line 275, in data_attach
    counts = scrape_count(links, country)
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\link_scrape.py", line 208, in scrape_count
    seek_count = review_volume(seek_soup, "Seek", seek_url)
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\link_scrape.py", line 188, in review_volume
    re.findall(r'total rating from ([0-9]+)', overview_data.text)[0])
IndexError: list index out of range


