Row Failed: 371

HTTP Error: 
404
 URL: https://www.seek.com.au/companies/laser-group-434193/reviewsTraceback (most recent call last):
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 144, in grab_HTML
    webpage = urlopen(req)
  File "C:\Users\Jamal135\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Jamal135\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\Jamal135\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\Jamal135\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\Jamal135\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\Jamal135\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 284, in grab_review_data
    dic = data_attach(dic, row, country)
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 235, in data_attach
    counts = scrape_count(links, country)
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 185, in scrape_count
    seek_soup = grab_HTML(seek_url, 1, "Seek")
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 147, in grab_HTML
    raise Exception(f'\nHTTP Error: \n{e.code}\n URL: {url}')
Exception: 
HTTP Error: 
404
 URL: https://www.seek.com.au/companies/laser-group-434193/reviews

Row Failed: 433
list index out of rangeTraceback (most recent call last):
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 284, in grab_review_data
    dic = data_attach(dic, row, country)
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 235, in data_attach
    counts = scrape_count(links, country)
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 186, in scrape_count
    seek_count = review_volume(seek_soup, "Seek")
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 168, in review_volume
    number_reviews = int((overview_data.text.split(
IndexError: list index out of range

Row Failed: 1890
list index out of rangeTraceback (most recent call last):
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 284, in grab_review_data
    dic = data_attach(dic, row, country)
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 235, in data_attach
    counts = scrape_count(links, country)
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 186, in scrape_count
    seek_count = review_volume(seek_soup, "Seek")
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 168, in review_volume
    number_reviews = int((overview_data.text.split(
IndexError: list index out of range

Row Failed: 1996
list index out of rangeTraceback (most recent call last):
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 284, in grab_review_data
    dic = data_attach(dic, row, country)
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 235, in data_attach
    counts = scrape_count(links, country)
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 186, in scrape_count
    seek_count = review_volume(seek_soup, "Seek")
  File "c:\Users\Jamal135\Documents\135Project\Company-List-Scrape\links\review_scrape.py", line 168, in review_volume
    number_reviews = int((overview_data.text.split(
IndexError: list index out of range

[371, 433, 1890, 1996]

